---
driver:
  name: vagrant
  synced_folders:
    - ['..', '/home/vagrant/incubator-hawq']
  customize:
    memory: 2048
    cpus: 4
  driver_config:
    network:
    - ["private_network", { type: "dhcp" }]

provisioner:
  name: nodes

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
      - 'recipe[java::default]'
    attributes: {
      java: {
        install_flavor: "openjdk",
        jdk_version: 8
      }
    }
  - name: centos-7.1
    run_list:
      - 'recipe[yum-epel::default]'
      - 'recipe[java::default]'
    attributes: {
      java: {
        install_flavor: "openjdk",
        jdk_version: 8
      }
    }
suites:
  - name: thrift
    run_list:
      - 'recipe[hawq_build::default]' 
      - 'recipe[hawq_build::thrift]' 
  - name: bison
    run_list:
      - 'recipe[hawq_build::default]' 
      - 'recipe[hawq_build::bison]' 
  - name: libhdfs3
    run_list:
      - 'recipe[hawq_build::default]' 
      - 'recipe[hawq_build::libhdfs3]'
  - name: libyarn
    attributes: {
      hawq_build: {
        libyarn: {
          git_repository: '/home/vagrant/incubator-hawq',
          git_revision: 'HAWQ-307'
        }
      }
    }
    run_list:
      - 'recipe[hawq_build::default]' 
      - 'recipe[hawq_build::libyarn]'
  - name: hawq
    attributes: {
      hawq_build: {
        git_repository: '/home/vagrant/incubator-hawq',
        git_revision: 'HAWQ-307',
        libyarn: {
          git_repository: '/home/vagrant/incubator-hawq',
          git_revision: 'HAWQ-307'
        }
      },
      bcpc: {
        management: {
          cidr: '10.0.2.15/24'
        },
        storage: {
          cidr: '10.0.2.15/24'
        },
        floating: {
          cidr: '10.0.2.15/24'
        },
        repos: {
          hortonworks: 'http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.3.4.0',
          hdp_utils: 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/ubuntu14'
        },
        hadoop: {
          distribution: {
            release: '2.3.4.0-3485'
          },
          java: '/usr/lib/jvm/java-1.8.0-openjdk-amd64/',
          skip_restart_coordination: true,
          cluster-name: 'test-kitchen',
          mounts: [0],
          hdfs: {
            dfs_replication_factor: 1,
            failed_volumes_tolerated: 0
          }
        }
      },
      java: {
        install_flavor: "openjdk",
        jdk_version: 8
      }
    }
    run_list:
      - 'recipe[bcpc::default]'
      - 'recipe[java::default]'
      - 'recipe[openssh::default]'
      - 'recipe[bcpc-hadoop::hdp_repo]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::namenode_no_HA]'
      - 'recipe[bcpc-hadoop::datanode]'
      - 'recipe[hawq_build::default]' 
      - 'recipe[hawq_build::thrift]' 
      - 'recipe[hawq_build::bison]' 
      - 'recipe[hawq_build::libhdfs3]'
      - 'recipe[hawq_build::libyarn]'
      - 'recipe[hawq_build::hawq]'
      - 'recipe[hawq_build::operate_hawq]'
