source "https://api.berkshelf.com"

cookbook 'hawq_build', path: 'hawq_build'
cookbook 'openssh'
cookbook 'bcpc', path: git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'bcpc-hadoop', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'bach_common', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'bach_krb5', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'bach_spark', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'bcpc_jmxtrans', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'hannibal', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'kafka-bcpc', git: 'https://github.com/cbaenziger/chef-bach.git', branch: 'test-kitchen'
cookbook 'dpkg_autostart', git: 'https://github.com/hw-cookbooks/dpkg_autostart.git'
cookbook 'cobblerd', git: 'https://github.com/bloomberg/cobbler-cookbook.git'
