source "https://api.berkshelf.com"

cookbook 'hawq_build', path: 'hawq_build'
cookbook 'openssh'
cookbook 'bcpc', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/bcpc'
cookbook 'bcpc-hadoop', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/bcpc-hadoop'
cookbook 'bach_common', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/bach_common'
cookbook 'bach_krb5', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/bach_krb5'
cookbook 'bach_spark', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/bach_spark'
cookbook 'bcpc_jmxtrans', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/bcpc_jmxtrans'
cookbook 'hannibal', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/hannibal'
cookbook 'kafka-bcpc', path: '/home/cwb/work/chef-bach-hdp2.3-kitchen/cookbooks/kafka-bcpc'
cookbook 'dpkg_autostart', git: 'https://github.com/hw-cookbooks/dpkg_autostart.git'
cookbook 'cobblerd', git: 'https://github.com/bloomberg/cobbler-cookbook.git'
