source "https://api.berkshelf.com"

cookbook 'hawq_build', path: 'hawq_build'
cookbook 'openssh'

def bach_cookbook(name, version = '>= 0.0.0', options = {})
  cookbook(name, version, {
    git: 'https://github.com/cbaenziger/chef-bach.git',
    branch: 'test-kitchen',
    rel: "cookbooks/#{name}"
   }.merge(options))
end

bach_cookbook 'bcpc'
bach_cookbook 'bcpc-hadoop'
bach_cookbook 'bach_common'
bach_cookbook 'bach_krb5'
bach_cookbook 'bach_spark'
bach_cookbook 'bcpc_jmxtrans'
bach_cookbook 'hannibal'
bach_cookbook 'kafka-bcpc'

cookbook 'dpkg_autostart', git: 'https://github.com/hw-cookbooks/dpkg_autostart.git'
cookbook 'cobblerd', git: 'https://github.com/bloomberg/cobbler-cookbook.git'
